export const tweetsData = [   
    {
        handle: `@TrollBot66756542 💎`,
        profilePic: `images/troll.jpg`,
        likes: 27,
        retweets: 10,
        tweetText: `Buy Bitcoin, ETH Make 💰💰💰 low low prices. 
            Guaranteed return on investment. HMU DMs open!!`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223ee',
    },    
    {
        handle: `@Elon ✅`,
        profilePic: `images/musk.png`,
        likes: 6500,
        retweets: 234,
        tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀`,
        replies: [
            {
                handle: `@TomCruise ✅`,
                profilePic: `images/tcruise.png`,
                tweetText: `Yes! Sign me up! 😎🛩`,
            },
            {
                handle: `@ChuckNorris ✅`,
                profilePic: `images/chucknorris.jpeg`,
                tweetText: `I went last year😴`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '3c23454ee-c0f5-9g9g-9c4b-77835tgs2',
    },
    {
        handle: `@NoobCoder12`,
        profilePic: `images/flower.png`,
        likes: 10,
        retweets: 3,
        tweetText: `Are you a coder if you only know HTML?`,
        replies: [
            {
                handle: `@StackOverflower ☣️`,
                profilePic: `images/overflow.png`,
                tweetText: `No. Obviosuly not. Go get a job in McDonald's.`,
            },
            {
                handle: `@YummyCoder64`,
                profilePic: `images/love.png`,
                tweetText: `You are wonderful just as you are! ❤️`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys45',
    },     
    {
        handle: `@DeepThoughts99`,
        profilePic: `images/thoughts.jpg`,
        likes: 456,
        retweets: 132,
        tweetText: `You ever open a tab and forget why you even opened it? That's modern life.`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '110ab32e-aaaa-bbbb-cccc-123456789001',
    },
    {
        handle: `@AIOverlord 🤖`,
        profilePic: `images/ai.png`,
        likes: 1024,
        retweets: 256,
        tweetText: `You may have beaten me at chess, but I control your thermostat now.`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '110ab32e-aaaa-bbbb-cccc-123456789002',
    },
    {
        handle: `@SleepyDev`,
        profilePic: `images/dev.png`,
        likes: 88,
        retweets: 14,
        tweetText: `Fixed one bug. Created three more. Progress.`,
        replies: [
            {
                handle: `@BugSquasher`,
                profilePic: `images/bug.png`,
                tweetText: `This is the way.`,
            }
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '110ab32e-aaaa-bbbb-cccc-123456789003',
    },
    {
        handle: `@CryptoCat 🐱`,
        profilePic: `images/cat.png`,
        likes: 420,
        retweets: 69,
        tweetText: `Just bought a token named $MEOW. Feeling bullish. 😼📈`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '110ab32e-aaaa-bbbb-cccc-123456789004',
    },
    {
        handle: `@404NotFound`,
        profilePic: `images/error.png`,
        likes: 0,
        retweets: 0,
        tweetText: `Tweet not found.`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '110ab32e-aaaa-bbbb-cccc-123456789005',
    },
    {
        handle: `@ZenMaster42 🧘`,
        profilePic: `images/zen.png`,
        likes: 900,
        retweets: 300,
        tweetText: `The answer lies within... unless you're looking for WiFi.`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '110ab32e-aaaa-bbbb-cccc-123456789006',
    },
    {
        handle: `@DailyJava ☕`,
        profilePic: `images/java.png`,
        likes: 77,
        retweets: 12,
        tweetText: `Starting the day with coffee and broken promises to my to-do list.`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '110ab32e-aaaa-bbbb-cccc-123456789007',
    },
    {
        handle: `@GamerDad97 🎮`,
        profilePic: `images/dad.png`,
        likes: 318,
        retweets: 55,
        tweetText: `Kids asleep. Time to game like I’m 19 again... for 20 mins before I fall asleep.`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '110ab32e-aaaa-bbbb-cccc-123456789008',
    },
    {
        handle: `@RealChefRamsey 🔪`,
        profilePic: `images/chef.png`,
        likes: 1234,
        retweets: 222,
        tweetText: `Your spaghetti is so undercooked it just joined a gym.`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '110ab32e-aaaa-bbbb-cccc-123456789009',
    },
]
